// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/telescope.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // ULID (Time-sorted ID)
	TraceId string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // The Shard Key
	// Indexed Fields
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Level   string `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	// The Payload
	Body          string `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`            // Raw JSON string
	Timestamp     int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix Nano timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_telescope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telescope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_telescope_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PushLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogRequest) Reset() {
	*x = PushLogRequest{}
	mi := &file_proto_telescope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogRequest) ProtoMessage() {}

func (x *PushLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telescope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogRequest.ProtoReflect.Descriptor instead.
func (*PushLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_telescope_proto_rawDescGZIP(), []int{1}
}

func (x *PushLogRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type PushLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushLogResponse) Reset() {
	*x = PushLogResponse{}
	mi := &file_proto_telescope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushLogResponse) ProtoMessage() {}

func (x *PushLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telescope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushLogResponse.ProtoReflect.Descriptor instead.
func (*PushLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_telescope_proto_rawDescGZIP(), []int{2}
}

func (x *PushLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushLogResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SearchLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Service       string                 `protobuf:"bytes,5,opt,name=service,proto3" json:"service,omitempty"`
	Level         string                 `protobuf:"bytes,6,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogRequest) Reset() {
	*x = SearchLogRequest{}
	mi := &file_proto_telescope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogRequest) ProtoMessage() {}

func (x *SearchLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telescope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogRequest.ProtoReflect.Descriptor instead.
func (*SearchLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_telescope_proto_rawDescGZIP(), []int{3}
}

func (x *SearchLogRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchLogRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SearchLogRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SearchLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SearchLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

type SearchLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*LogEntry            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogResponse) Reset() {
	*x = SearchLogResponse{}
	mi := &file_proto_telescope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogResponse) ProtoMessage() {}

func (x *SearchLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telescope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogResponse.ProtoReflect.Descriptor instead.
func (*SearchLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_telescope_proto_rawDescGZIP(), []int{4}
}

func (x *SearchLogResponse) GetResults() []*LogEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_telescope_proto protoreflect.FileDescriptor

const file_proto_telescope_proto_rawDesc = "" +
	"\n" +
	"\x15proto/telescope.proto\x12\ttelescope\"\x97\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"?\n" +
	"\x0ePushLogRequest\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.telescope.LogEntryR\aentries\"P\n" +
	"\x0fPushLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa8\x01\n" +
	"\x10SearchLogRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x18\n" +
	"\aservice\x18\x05 \x01(\tR\aservice\x12\x14\n" +
	"\x05level\x18\x06 \x01(\tR\x05level\"B\n" +
	"\x11SearchLogResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.telescope.LogEntryR\aresults2\x98\x01\n" +
	"\n" +
	"LogService\x12A\n" +
	"\bPushLogs\x12\x19.telescope.PushLogRequest\x1a\x1a.telescope.PushLogResponse\x12G\n" +
	"\n" +
	"SearchLogs\x12\x1b.telescope.SearchLogRequest\x1a\x1c.telescope.SearchLogResponseBHZFgithub.com/Abhinnavverma/Telescope-Distributed-Log-Search-Engine/protob\x06proto3"

var (
	file_proto_telescope_proto_rawDescOnce sync.Once
	file_proto_telescope_proto_rawDescData []byte
)

func file_proto_telescope_proto_rawDescGZIP() []byte {
	file_proto_telescope_proto_rawDescOnce.Do(func() {
		file_proto_telescope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telescope_proto_rawDesc), len(file_proto_telescope_proto_rawDesc)))
	})
	return file_proto_telescope_proto_rawDescData
}

var file_proto_telescope_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_telescope_proto_goTypes = []any{
	(*LogEntry)(nil),          // 0: telescope.LogEntry
	(*PushLogRequest)(nil),    // 1: telescope.PushLogRequest
	(*PushLogResponse)(nil),   // 2: telescope.PushLogResponse
	(*SearchLogRequest)(nil),  // 3: telescope.SearchLogRequest
	(*SearchLogResponse)(nil), // 4: telescope.SearchLogResponse
}
var file_proto_telescope_proto_depIdxs = []int32{
	0, // 0: telescope.PushLogRequest.entries:type_name -> telescope.LogEntry
	0, // 1: telescope.SearchLogResponse.results:type_name -> telescope.LogEntry
	1, // 2: telescope.LogService.PushLogs:input_type -> telescope.PushLogRequest
	3, // 3: telescope.LogService.SearchLogs:input_type -> telescope.SearchLogRequest
	2, // 4: telescope.LogService.PushLogs:output_type -> telescope.PushLogResponse
	4, // 5: telescope.LogService.SearchLogs:output_type -> telescope.SearchLogResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_telescope_proto_init() }
func file_proto_telescope_proto_init() {
	if File_proto_telescope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telescope_proto_rawDesc), len(file_proto_telescope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telescope_proto_goTypes,
		DependencyIndexes: file_proto_telescope_proto_depIdxs,
		MessageInfos:      file_proto_telescope_proto_msgTypes,
	}.Build()
	File_proto_telescope_proto = out.File
	file_proto_telescope_proto_goTypes = nil
	file_proto_telescope_proto_depIdxs = nil
}
