# Stage 1: Build
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the Producer binary
RUN CGO_ENABLED=0 GOOS=linux go build -o producer-node cmd/producer/main.go

# Stage 2: Run
FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/producer-node .

# Command to run
CMD ["./producer-node"]