FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# Build the Search API
RUN CGO_ENABLED=0 GOOS=linux go build -o search-api cmd/searchAPI/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/search-api .

# Expose HTTP Port
EXPOSE 8080
CMD ["./search-api"]